'use strict';

const MAX_UINT64 = 18446744073709551615n;
const ADAMANT_ADDRESS_PATTERN = /^U[0-9]{6,20}$/i;
const PUBLIC_KEY_PATTERN = /^[a-f0-9]{64}$/i;
const UNSIGNED_DECIMAL_PATTERN = /^(0|[1-9][0-9]*)$/;
const DELEGATE_SEARCH_PATTERN = /^[a-z0-9!@$&_.]{1,20}$/i;

/** Public request validation failure safe to return to an API client. */
class ValidationError extends TypeError {
  /**
   * @param {string} message Bounded public error message
   */
  constructor(message) {
    super(message);
    this.name = 'ValidationError';
  }
}

/**
 * Check whether a value is a syntactically valid ADAMANT address.
 *
 * Addresses are unsigned 64-bit account identifiers prefixed with `U`.
 * Lowercase prefixes remain accepted for existing Explorer deep links.
 * @param {*} value Candidate address
 * @returns {boolean} Whether the value is safe to forward to the Node API
 */
function isAdamantAddress(value) {
  if (typeof value !== 'string' || !ADAMANT_ADDRESS_PATTERN.test(value)) {
    return false;
  }

  return BigInt(value.slice(1)) <= MAX_UINT64;
}

/**
 * Normalize a validated ADAMANT address to its canonical uppercase prefix.
 * @param {string} value Valid ADAMANT address
 * @returns {string} Canonical address
 * @throws {ValidationError} When the address is malformed or outside uint64 range
 */
function normalizeAdamantAddress(value) {
  if (!isAdamantAddress(value)) {
    throw new ValidationError('Missing/Invalid address parameter');
  }

  return `U${value.slice(1)}`;
}

/**
 * Check whether a value is a 32-byte hexadecimal ADAMANT public key.
 * @param {*} value Candidate public key
 * @returns {boolean} Whether the public key is valid
 */
function isPublicKey(value) {
  return typeof value === 'string' && PUBLIC_KEY_PATTERN.test(value);
}

/**
 * Check whether a value is a canonical unsigned 64-bit decimal identifier.
 * @param {*} value Candidate block or transaction id
 * @returns {boolean} Whether the identifier is safe to forward
 */
function isUnsignedIdentifier(value) {
  if (typeof value !== 'string' || !UNSIGNED_DECIMAL_PATTERN.test(value)) {
    return false;
  }

  return BigInt(value) <= MAX_UINT64;
}

/**
 * Check whether a value is a bounded delegate-name search fragment.
 * @param {*} value Candidate delegate search text
 * @returns {boolean} Whether the search can be forwarded
 */
function isDelegateSearch(value) {
  return typeof value === 'string' && DELEGATE_SEARCH_PATTERN.test(value);
}

/**
 * Parse a strict integer parameter without accepting prefixes or coercible
 * objects such as `12junk`, arrays, or exponential notation.
 *
 * Empty strings are treated as omitted only when a default is supplied,
 * preserving optional query parameters generated by the current UI.
 * @param {*} value Raw parameter
 * @param {Object} options Parsing constraints
 * @param {string} options.name Public parameter name used in errors
 * @param {number} [options.defaultValue] Value used when omitted
 * @param {number} [options.minimum=0] Inclusive lower bound
 * @param {number} [options.maximum=Number.MAX_SAFE_INTEGER] Inclusive upper bound
 * @returns {number} Parsed integer
 * @throws {ValidationError} When the value is missing, malformed, or out of bounds
 */
function parseIntegerParameter(
  value,
  { name, defaultValue, minimum = 0, maximum = Number.MAX_SAFE_INTEGER },
) {
  if ((value === undefined || value === '') && defaultValue !== undefined) {
    return defaultValue;
  }

  const isCanonicalString = typeof value === 'string' && UNSIGNED_DECIMAL_PATTERN.test(value);
  const isIntegerNumber = typeof value === 'number' && Number.isSafeInteger(value);

  if (!isCanonicalString && !isIntegerNumber) {
    throw new ValidationError(`Missing/Invalid ${name} parameter`);
  }

  const parsed = Number(value);

  if (!Number.isSafeInteger(parsed) || parsed < minimum || parsed > maximum) {
    throw new ValidationError(`Missing/Invalid ${name} parameter`);
  }

  return parsed;
}

/**
 * Validate the public query object against an endpoint-specific allowlist.
 *
 * Values must be scalar strings. Express represents duplicate query keys as
 * arrays, so this also blocks type confusion before handlers or Node requests.
 * @param {*} query Express query object
 * @param {Array<string>} allowedKeys Accepted query names
 * @returns {string|null} Public validation error, or `null` when valid
 */
function validateQueryKeys(query, allowedKeys) {
  if (!query || typeof query !== 'object' || Array.isArray(query)) {
    return 'Missing/Invalid query parameters';
  }

  const allowed = new Set(allowedKeys);

  for (const key of Object.keys(query)) {
    if (!allowed.has(key)) {
      return `Unexpected ${key} query parameter`;
    }

    if (typeof query[key] !== 'string') {
      return `Missing/Invalid ${key} parameter`;
    }
  }

  return null;
}

module.exports = {
  ValidationError,
  isAdamantAddress,
  isDelegateSearch,
  isPublicKey,
  isUnsignedIdentifier,
  normalizeAdamantAddress,
  parseIntegerParameter,
  validateQueryKeys,
};
