<script setup>
// Block details page: summary table plus the block's transactions.
import { ref, watch } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import { useNetworkStore } from '../stores/network';
import { apiGetOrThrow } from '../lib/api';
import { useLessMore } from '../lib/lessMore';
import { formatCurrency, formatTimestamp } from '../lib/format';
import CopyButton from '../components/CopyButton.vue';
import TransactionsList from '../components/TransactionsList.vue';

const route = useRoute();
const router = useRouter();
const network = useNetworkStore();

const block = ref(null);
const txs = ref(null);

/** Loads the block or falls back to the home page when it is unknown. */
async function getBlock(blockId) {
  block.value = null;

  try {
    const data = await apiGetOrThrow('/api/getBlock', { blockId });
    block.value = data.block;

    txs.value = useLessMore({
      url: '/api/getTransactionsByBlock',
      key: 'transactions',
      parent: 'block',
      params: { blockId },
    });
    txs.value.loadData();
  } catch {
    router.replace('/');
  }
}

watch(() => route.params.blockId, getBlock, { immediate: true });

/** Rows of the summary table: label plus rendered value. */
const summary = [
  { label: 'Transactions', value: (b) => b.numberOfTransactions },
  { label: 'Confirmations', value: (b) => b.confirmations },
  { label: 'Height', value: (b) => b.height },
  { label: 'Reward', value: (b) => amount(b.reward, network.decimalPlaces), currency: true },
  { label: 'Total Fee', value: (b) => amount(b.totalFee), currency: true },
  {
    label: 'Total Forged',
    value: (b) => amount(b.totalForged, network.decimalPlaces),
    currency: true,
  },
  {
    label: 'Total Amount',
    value: (b) => amount(b.totalAmount, network.decimalPlaces),
    currency: true,
  },
  { label: 'Timestamp', value: (b) => formatTimestamp(b.timestamp) },
];

/** Shorthand for currency formatting in the summary rows. */
function amount(value, decimals) {
  return formatCurrency(value, network.currency, decimals);
}
</script>

<template>
  <section>
    <h1>
      Block <small class="ellipsis">{{ route.params.blockId }}</small>
    </h1>

    <div v-if="!block" class="text-muted">Loading block <span class="spinner"></span></div>

    <template v-else>
      <div class="well ellipsis">
        <strong>Block ID</strong>
        <span class="txid text-muted">{{ block.id }}</span>
        <CopyButton :text="block.id" />
      </div>

      <h2>Summary</h2>
      <div class="table-responsive">
        <table class="table summary">
          <tbody>
            <tr v-for="row in summary" :key="row.label">
              <td>
                <strong>{{ row.label }}</strong>
              </td>
              <td class="text-right">
                {{ row.value(block) }}
                <span v-if="row.currency" class="text-muted">{{ network.currency.symbol }}</span>
              </td>
            </tr>
            <tr v-if="block.nextBlock">
              <td><strong>Next block</strong></td>
              <td class="text-right">
                <router-link :to="`/block/${block.nextBlock}`">{{ block.nextBlock }}</router-link>
              </td>
            </tr>
            <tr v-if="block.previousBlock">
              <td><strong>Previous block</strong></td>
              <td class="text-right">
                <router-link :to="`/block/${block.previousBlock}`">
                  {{ block.previousBlock }}
                </router-link>
              </td>
            </tr>
            <tr>
              <td><strong>Generated by</strong></td>
              <td class="text-right">
                <router-link :to="`/delegate/${block.generatorId}`">
                  {{ block.delegate?.username || block.generatorId }}
                </router-link>
              </td>
            </tr>
          </tbody>
        </table>
      </div>

      <h2>Transactions</h2>
      <TransactionsList v-if="txs" :txs="txs" />
    </template>
  </section>
</template>
