<script setup>
// Paginated list of the latest blocks; page number comes from the route.
import { ref, watch } from 'vue';
import { useRoute } from 'vue-router';
import { useNetworkStore } from '../stores/network';
import { apiGet } from '../lib/api';
import { createBlockRefreshTrigger } from '../lib/blockRefresh';
import { formatCurrency, formatInteger } from '../lib/format';
import TimestampValue from '../components/TimestampValue.vue';

const route = useRoute();
const network = useNetworkStore();

const blocks = ref(null);

/**
 * Loads one page of blocks. The API takes a row offset (`n`); pages are
 * 20 blocks each, matching the legacy explorer. The server versions this
 * endpoint's Redis cache by its trusted latest block identity.
 * @param {number} page 1-based page number
 */
async function getLastBlocks(page) {
  const offset = page > 1 ? (page - 1) * 20 : 0;

  try {
    const data = await apiGet('/api/getLastBlocks', { n: offset });

    blocks.value = data.success ? data.blocks : [];
  } catch {
    blocks.value = [];
  }
}

watch(
  () => route.params.page,
  (page) => getLastBlocks(parseInt(page, 10) || 1),
  { immediate: true },
);

const refreshOnBlock = createBlockRefreshTrigger(
  () => getLastBlocks(parseInt(route.params.page, 10) || 1),
  network.latestBlock,
);

watch(
  () => network.latestBlock,
  (block) => void refreshOnBlock(block),
);
</script>

<template>
  <section>
    <div class="page-header">
      <h1>
        Blocks
        <small v-if="blocks && blocks.length > 1">
          {{ formatInteger(blocks[0].height) }} →
          {{ formatInteger(blocks[blocks.length - 1].height) }}
        </small>
      </h1>
      <hr />
    </div>

    <div class="table-responsive">
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Id</th>
            <th class="text-right">Height</th>
            <th class="text-right hide-sm">Timestamp</th>
            <th class="text-right">
              <span class="hide-sm">Transactions</span><span class="show-sm">TXS</span>
            </th>
            <th class="text-right hide-md">Generated by</th>
            <th class="text-right hide-md">Amount ({{ network.currency.symbol }})</th>
            <th class="text-right hide-md">Forged ({{ network.currency.symbol }})</th>
          </tr>
        </thead>
        <tbody>
          <tr v-if="!blocks">
            <td colspan="7">Waiting for blocks <span class="spinner"></span></td>
          </tr>
          <tr v-for="block in blocks" :key="block.id">
            <td>
              <router-link class="ellipsis" :to="`/block/${block.id}`">{{ block.id }}</router-link>
            </td>
            <td class="text-right">{{ formatInteger(block.height) }}</td>
            <td class="text-right hide-sm"><TimestampValue :timestamp="block.timestamp" /></td>
            <td class="text-right">{{ formatInteger(block.transactionsCount) }}</td>
            <td class="text-right hide-md">
              <router-link :to="`/delegate/${block.generator}`">
                {{ block.delegate?.username || block.generator }}
              </router-link>
            </td>
            <td class="text-right hide-md">
              {{ formatCurrency(block.totalAmount, network.currency, network.decimalPlaces) }}
            </td>
            <td class="text-right hide-md">
              {{ formatCurrency(block.totalForged, network.currency) }}
            </td>
          </tr>
        </tbody>
      </table>
    </div>

    <h2 v-if="blocks && !blocks.length" class="text-center text-muted">No blocks yet.</h2>
  </section>
</template>
