<script setup>
// Paginated list of the latest blocks; page number comes from the route.
import { ref, watch } from 'vue';
import { useRoute } from 'vue-router';
import { useNetworkStore } from '../stores/network';
import { apiGet } from '../lib/api';
import { formatCurrency, formatTimestamp } from '../lib/format';

const route = useRoute();
const network = useNetworkStore();

const blocks = ref(null);
const pagination = ref(null);

/**
 * Loads one page of blocks. The API takes a row offset (`n`); pages are
 * 20 blocks each, matching the legacy explorer.
 * @param {number} page 1-based page number
 */
async function getLastBlocks(page) {
  const offset = page > 1 ? (page - 1) * 20 : 0;

  try {
    const data = await apiGet('/api/getLastBlocks', { n: offset });

    blocks.value = data.success ? data.blocks : [];
    pagination.value = data.pagination ?? null;
  } catch {
    blocks.value = [];
  }
}

watch(
  () => route.params.page,
  (page) => getLastBlocks(parseInt(page, 10) || 1),
  { immediate: true },
);
</script>

<template>
  <section>
    <div class="page-header">
      <h1>
        Blocks
        <small v-if="blocks && blocks.length > 1">
          {{ blocks[0].height }} → {{ blocks[blocks.length - 1].height }}
        </small>
      </h1>
      <hr />
    </div>

    <div class="table-responsive">
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Id</th>
            <th class="text-right">Height</th>
            <th class="text-right hide-sm">Timestamp</th>
            <th class="text-right hide-sm">Transactions</th>
            <th class="text-right hide-md">Generated by</th>
            <th class="text-right hide-md">Amount ({{ network.currency.symbol }})</th>
            <th class="text-right hide-md">Forged ({{ network.currency.symbol }})</th>
          </tr>
        </thead>
        <tbody>
          <tr v-if="!blocks">
            <td colspan="7">Waiting for blocks <span class="spinner"></span></td>
          </tr>
          <tr v-for="block in blocks" :key="block.id">
            <td>
              <router-link class="ellipsis" :to="`/block/${block.id}`">{{ block.id }}</router-link>
            </td>
            <td class="text-right">{{ block.height }}</td>
            <td class="text-right hide-sm">{{ formatTimestamp(block.timestamp) }}</td>
            <td class="text-right hide-sm">{{ block.transactionsCount }}</td>
            <td class="text-right hide-md">
              <router-link :to="`/delegate/${block.generator}`">
                {{ block.delegate?.username || block.generator }}
              </router-link>
            </td>
            <td class="text-right hide-md">
              {{ formatCurrency(block.totalAmount, network.currency, network.decimalPlaces) }}
            </td>
            <td class="text-right hide-md">
              {{ formatCurrency(block.totalForged, network.currency) }}
            </td>
          </tr>
        </tbody>
      </table>
    </div>

    <div v-if="pagination && (pagination.more || pagination.before)" class="pagination-links">
      <router-link
        v-if="pagination.before"
        class="btn btn-primary"
        :to="`/blocks/${pagination.previousPage}`"
      >
        Previous page
      </router-link>
      <router-link
        v-if="pagination.more && pagination.nextPage !== 0"
        class="btn btn-primary"
        :to="`/blocks/${pagination.nextPage}`"
      >
        Next page
      </router-link>
    </div>

    <h2 v-if="blocks && !blocks.length" class="text-center text-muted">No blocks yet.</h2>
  </section>
</template>
