Feature: Block page
  Scenario: should show title, summary, and transactions
    Given I'm on page "/block/6524861224470851795"
    Then I should see "Block  6524861224470851795" in "h1" html element
    And I should see table "summary" containing:
      | Transactions  | 103                  |
      | Confirmations | 12425                |
      | Height        | 1                    |
      | Reward        | 0 LSK                |
      | Total Fee     | 0 LSK                |
      | Total Forged  | 0 LSK                |
      | Total Amount  | 100,000,000 LSK      |
      | Timestamp     | 2016/05/24 19:00:00  |
      | Generated by  | 1085993630748340485L |

