Feature: Block page
  Scenario: should show title, summary, and transactions
    Given I'm on page "/block/6524861224470851795"
    Then I should see "Block  6524861224470851795" in "h1" html element
    And I should see "Home Blocks Block" in "breadcrumb" element
    And I should see table "summary" containing:
      | Transactions  | 103                        |
      | Confirmations | /\d+/                      |
      | Height        | 1                          |
      | Reward        | 0 LSK                      |
      | Total Fee     | 0 LSK                      |
      | Total Forged  | 0 LSK                      |
      | Total Amount  | 100,000,000 LSK            |
      | Timestamp     | /2016\/05\/24 \d\d:00:00/  |
      | Generated by  | 1085993630748340485L       |
    And I should see table "transactions" with 50 rows starting with:
      | Transaction ID       | Date                      | Sender            | Recipient             | Amount | Fee   | Confirmations |
      |----------------------|---------------------------|-------------------|-----------------------|--------|-------|---------------|
      | /\d{18,20}/          | /2016\/05\/24 \d\d:00:00/ | /genesis_\d{1,3}/ | Delegate registration | 0 LSK  | 0 LSK | Confirmed     |
      | /\d{18,20}/          | /2016\/05\/24 \d\d:00:00/ | /genesis_\d{1,3}/ | Delegate registration | 0 LSK  | 0 LSK | Confirmed     |
      | /\d{18,20}/          | /2016\/05\/24 \d\d:00:00/ | /genesis_\d{1,3}/ | Delegate registration | 0 LSK  | 0 LSK | Confirmed     |
      | /\d{18,20}/          | /2016\/05\/24 \d\d:00:00/ | /genesis_\d{1,3}/ | Delegate registration | 0 LSK  | 0 LSK | Confirmed     |
      | /\d{18,20}/          | /2016\/05\/24 \d\d:00:00/ | /genesis_\d{1,3}/ | Delegate registration | 0 LSK  | 0 LSK | Confirmed     |

  # ignored because it the feature is broken
  @ignore
  Scenario: should allow to load more transactions
    Given I'm on page "/block/6524861224470851795"
    When I scroll to "more button"
    And I click "more button"
    Then I should see table "transactions" with 100 rows

  # ignored because it the feature is broken
  @ignore
  Scenario: should allow to load less transactions
    Given I'm on page "/block/6524861224470851795"
    When I scroll to "more button"
    And I click "more button"
    And I should see table "transactions" with 100 rows
    And I scroll to "less button"
    And I click "less button"
    Then I should see table "transactions" with 50 rows
